version: '3.5'

services:
  mongodb:
    image: mongo
    container_name: mongo-db
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./mongodb/database:/data/db
    ports:
      # - 27017:27017
      - 27888:27017
    restart: unless-stopped
#
#
#
#
#
#
#
# docker run -d  --name mongo-on-docker  -p 27888:27017 -e MONGO_INITDB_ROOT_USERNAME=mongoadmin -e MONGO_INITDB_ROOT_PASSWORD=secret mongo
# ```

#     docker run runs the image and starts the container;
#     -d runs the container in background, so that we are free to use the current terminal instance;
#     --name mongo-on-docker defines a friendly name for the container;
#     -p 27888:27017 declares that the local port 27888 is mapped to the internal 27017 port;
#     -e MONGO_INITDB_ROOT_USERNAME=mongoadmin sets the root username (-e sets the environment variables);
#     -r MONGO_INITDB_ROOT_PASSWORD=secret sets the root password;
#     mongo is the name of the image to run;

